### ISSUE TITLE
make LaTeX bigger

### ISSUE THREAD

**Issue by kohlhase** [KWARC/mathhub_docker#1]
In GenCS I hit the memory bounds in pdflatex. But they can be extended. 

I am currently using the following ones in `/usr/local/texlive/2014/texmf.cnf`:

```
% (Public domain.)
% This texmf.cnf file should contain only your personal changes from the
% original texmf.cnf (for example, as chosen in the installer).
%
% That is, if you need to make changes to texmf.cnf, put your custom
% settings in this file, which is .../texlive/YYYY/texmf.cnf, rather than
% the distributed file (which is .../texlive/YYYY/texmf-dist/web2c/texmf.cnf).
% And include *only* your changed values, not a copy of the whole thing!
%
TEXMFHOME = ~/Library/texmf
TEXMFVAR = ~/Library/texlive/2014/texmf-var
TEXMFCONFIG = ~/Library/texlive/2014/texmf-config
max_in_open = 50        % simultaneous input files and error insertions, 
param_size = 20000      % simultaneous macro parameters, also applies to MP
nest_size = 1000        % simultaneous semantic levels (e.g., groups)
stack_size = 10000      % simultaneous input sources
%extra_mem_top = 2000000
%extra_mem_bot = 4000000
main_memory = 12000000
```

(important are `main_memory` and `max_in_open`, they can just be changed in  `/usr/local/texlive/2014/texmf.cnf` (or somewhere similar) and then we need to run 

```
sudo fmtutil-sys --all
```

And then things should be bigger.

**Comment by kohlhase** [comment]
@tkw1536, you said that you would be releasing a new version of the docker at some point, then this change would be good to have. Otherwise it is not so urgent.

**Comment by tkw1536** [comment]
@kohlhase Should this ticket not be on localmh_docker? MathHub_docker has no pdflatex

**Comment by kohlhase** [comment]
absolutely, that is what I intended. sorry for the confusion.

**Comment by m-iancu** [comment]
I will close this then, @tkw1536 you can recreate in on localmh_docker if needed.
